<div class="page-content">
    <h1 class="card-title"> Dados do Grupo </h1>
    <div class="row pb-3">
        <?php echo $this->tag->image([$grupo->foto, 'class' => 'quadro col-lg-6 mb-4 mx-auto']); ?>
        <?php echo $this->tag->form(['action' => '', 'class' => 'form col-lg-6', 'enctype' => 'multipart/form-data']); ?>
            <div class="mb-4">
                <label for="imagemGrupo">Foto do Grupo</label>
                <input type="file" class="form-control-file" name="imagemGrupo" accept="image/png, image/jpg, image/jpeg">
            </div>

            <div class="mb-4">
                <label for="nome">Nome</label>
                <input type="text" class="form-control" name="nome" value="<?php echo $grupo->nome?>" required>
            </div>

            <div class="mb-4">
                <label for="descricao">Descrição</label>
                <?php echo $this->tag->textArea([
                    "descricao",
                    "maxlength"     => 255,
                    "placeholder"   => "(Opcional)",
                    "value"         => $grupo->descricao,
                    "class"         => "form-control",
                ]); ?>
            </div>

            <div class="mb-4">
                <label for="website">Website</label>
                <?php echo $this->tag->textField([
                    "website",
                    "placeholder"   => "(Opcional)",
                    "class"         => "form-control",
                    "value"         => $grupo->website,
                ]); ?>
            </div>

            <div class="mb-4">
                <label for="tags">Interesses (#Tags) </label>
                <?php echo $this->tag->textArea([
                    "tags",
                    "maxlength"     => 255,
                    "placeholder"   => "#ceia #contrição #jovem",
                    "value"         => $grupo->tags,
                    "class"         => "form-control",
                ]); ?>
            </div>
            <button type="submit" class="btn btn-success">Atualizar</button>
        </form>
    </div>
</div>