<div class="text-center">
  <?php $this->flashSession->output(); ?>
    <?= $this->tag->form(['action' => 'login/entrar', 'class' => 'form-signin'])?>
      <?= $this->tag->image([
          'img/logo.png',
          'class' => 'mb-4',
          'style' => "width: 100%",
          
      ]); ?>
      <h1 class="h3 mb-3 font-weight-normal">Login</h1>

      <label for="email" class="sr-only">Email</label>
      <input type="email" name="email" id="email" class="form-control" placeholder="Email" required autofocus>
      <label for="senha" class="sr-only">Senha</label>
      <input type="password" name="senha" id="senha" class="form-control" placeholder="Senha" required>
      <input type="submit" class="btn btn-lg btn-primary btn-block mt-4 mb-1" value="Entrar">
      <?php 
        echo $this->tag->linkTo([
          'usuario/novo',
          'Cadastre-se',
          'class' => 'mt-2 mb-3 text-muted',
        ])
      ?>
    </form>
</div>